#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Egorov\SumCommand;

$app = new Application('Welcome from Console', 'v.1.0.0');
$app->add(new SumCommand());
$app->run();

